language: node_js
node_js:
  - "10"
# cache:
#   directories:
#     - node_modules
notification:
  email:
    recipients:
      - yunindyo.prabowo@gmail.com
    on_success: always
    on_failure: always
git:
  depth: 3
deploy:
  provider: pages
  skip-cleanup: false
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  target-branch: master
  on:
    branch: develop

before_script:
  - "npm install -g gatsby-cli"
  - "npm install"

script:
  - "gatsby build --prefix-paths --verbose"
