language: node_js
node_js:
  - "9"
cache:
  directories:
  - ~/.npm
notification:
  email:
    recipients:
      - dyo.ndutz@gmail.com
    on_success: always
    on_failure: always
git:
  depth: 3
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  target-branch: master
  on:
    branch: develop
script:
  - "yarn build"
