language: node_js
node_js:
  - "9"
cache:
  directories:
    - node_modules
notification:
  email:
    recipients:
      - dyo.ndutz@gmail.com
    on_success: always
    on_failure: always
git:
  depth: 3

before_script:
  - "npm install -g gatsby-cli"
  - "npm install"
script:
  - npm build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  keep-history: true
  target-branch: master
  on:
    branch: develop


