language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
notification:
  email:
    recipients:
      - dyo.ndutz@gmail.com
    on_success: always
    on_failure: always
git:
  depth: 3
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  target-branch: master
  on:
    branch: develop

before_script:
  - "npm install -g gatsby-cli"

script:
  - "npm install"
  - "gatsby build --prefix-paths --verbose"
