name: Gatsby Publish

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: xmflsct/action-publish-gatsby@v1
        with:
          publishBranch: 'master'
          access-token: ${{ secrets.ACCESS_TOKEN }}
