name: Gatsby Publish

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: xxninjabunnyxx/gatsby-push-to-github-pages-action@main
        with:
          publishBranch: 'master'
          token: ${{ secrets.ACCESS_TOKEN }}
          name: 'ypraw'
          email: 'dyo.ndutz@gmail.com'
