on:
  push:
    branches:
      develop
jobs:
  build:
    name: Build Gatsby Site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Gatsby Publish
      uses: enriikke/gatsby-gh-pages-action@v2
      with:
        access-token: ${{ secrets.BUILD_SECRET }}
        deploy-branch: master
